[package]
name = "reverse_geocoder"
version = "2.0.1"
authors = ["Grant Miner <ggcode1@users.noreply.github.com>"]
edition = "2018"
description = "Offline reverse geocoder library."
license = "MIT OR Apache-2.0"
repository = "https://github.com/ggcode1/rrgeo"
categories = ["science"]
keywords = ["reverse", "geocoding", "geocoder", "location"]

[dependencies]
kdtree = "^0.6"
quick-csv = "^0.1"
rustc-serialize = "^0.3"
# time = "0.2.9"
serde = "^1.0"
serde_derive = "^1.0"

[dev-dependencies]
criterion = "0.3"
lazy_static = "^1.4"

[lib]
name = "reverse_geocoder"
path = "src/reverse_geocoder.rs"

[[bench]]
name = "benchmark"
harness = false
