[package]
name = "rrgeo-cmd"
version = "0.1.0"
authors = ["Grant Miner <ggcode1@users.noreply.github.com>"]
edition = "2018"

[dependencies]
reverse_geocoder = { path = "../reverse-geocoder" }
time = "^0.2.16"

[[bin]]
name = "rrgeo-cmd"
path = "src/cmdline.rs"
